# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_coffee(object):
    def setupUi(self, coffee):
        coffee.setObjectName("coffee")
        coffee.resize(889, 569)
        self.show_btn = QtWidgets.QPushButton(coffee)
        self.show_btn.setGeometry(QtCore.QRect(360, 490, 161, 61))
        self.show_btn.setObjectName("show_btn")
        self.tableWidget = QtWidgets.QTableWidget(coffee)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 891, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.add_btn = QtWidgets.QPushButton(coffee)
        self.add_btn.setGeometry(QtCore.QRect(550, 490, 171, 61))
        self.add_btn.setObjectName("add_btn")

        self.retranslateUi(coffee)
        QtCore.QMetaObject.connectSlotsByName(coffee)

    def retranslateUi(self, coffee):
        _translate = QtCore.QCoreApplication.translate
        coffee.setWindowTitle(_translate("coffee", "coffee"))
        self.show_btn.setText(_translate("coffee", "Показать"))
        self.add_btn.setText(_translate("coffee", "Редактировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    coffee = QtWidgets.QWidget()
    ui = Ui_coffee()
    ui.setupUi(coffee)
    coffee.show()
    sys.exit(app.exec_())
